-- CreateTable: All tables generated from schema.prisma
-- This file is auto-generated by `prisma migrate dev`
-- Run: npx prisma migrate deploy

CREATE TABLE IF NOT EXISTS "groups" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "color" TEXT NOT NULL DEFAULT 'gold',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "groups_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "teams" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "emoji" TEXT NOT NULL DEFAULT '🏏',
  "captain" TEXT NOT NULL DEFAULT '',
  "groupId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "squad_members" (
  "id" TEXT NOT NULL,
  "teamId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'bat',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "squad_members_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "matches" (
  "id" TEXT NOT NULL,
  "stage" TEXT NOT NULL DEFAULT 'group',
  "groupId" TEXT,
  "matchNo" TEXT NOT NULL DEFAULT '',
  "team1Id" TEXT NOT NULL,
  "team2Id" TEXT NOT NULL,
  "date" TEXT NOT NULL DEFAULT '',
  "time" TEXT NOT NULL DEFAULT '',
  "year" INTEGER NOT NULL DEFAULT 2026,
  "venue" TEXT NOT NULL DEFAULT 'Pattan Cricket Ground',
  "status" TEXT NOT NULL DEFAULT 'upcoming',
  "result" TEXT NOT NULL DEFAULT '',
  "score1" TEXT NOT NULL DEFAULT '',
  "score2" TEXT NOT NULL DEFAULT '',
  "overs" INTEGER NOT NULL DEFAULT 10,
  "highlights" JSONB NOT NULL DEFAULT '{}',
  "innings1" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "matches_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "players" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "emoji" TEXT NOT NULL DEFAULT '🏏',
  "teamId" TEXT,
  "role" TEXT NOT NULL DEFAULT 'batting',
  "runs" INTEGER NOT NULL DEFAULT 0,
  "wickets" INTEGER NOT NULL DEFAULT 0,
  "strikeRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "economy" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "best" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "players_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ball_events" (
  "id" TEXT NOT NULL,
  "matchId" TEXT NOT NULL,
  "innings" INTEGER NOT NULL DEFAULT 1,
  "over" INTEGER NOT NULL DEFAULT 0,
  "ball" INTEGER NOT NULL DEFAULT 0,
  "runs" INTEGER NOT NULL DEFAULT 0,
  "isWicket" BOOLEAN NOT NULL DEFAULT false,
  "isWide" BOOLEAN NOT NULL DEFAULT false,
  "isNoBall" BOOLEAN NOT NULL DEFAULT false,
  "isBye" BOOLEAN NOT NULL DEFAULT false,
  "batsman" TEXT NOT NULL DEFAULT '',
  "bowler" TEXT NOT NULL DEFAULT '',
  "commentary" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ball_events_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sentiments" (
  "id" TEXT NOT NULL,
  "matchId" TEXT NOT NULL,
  "teamId" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "sentiments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "sentiments_matchId_sessionId_key" UNIQUE ("matchId", "sessionId")
);

CREATE TABLE IF NOT EXISTS "ads" (
  "id" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ads_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "polls" (
  "id" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'Poll',
  "question" TEXT NOT NULL,
  "options" JSONB NOT NULL DEFAULT '[]',
  "votes" JSONB NOT NULL DEFAULT '[]',
  "votedBy" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "polls_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "orgs" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT '',
  "emoji" TEXT NOT NULL DEFAULT '🏢',
  "since" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "orgs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "rules" (
  "id" SERIAL NOT NULL,
  "content" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "rules_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "announcements" (
  "id" SERIAL NOT NULL,
  "content" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "announcements_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "gallery" (
  "id" TEXT NOT NULL,
  "emoji" TEXT NOT NULL DEFAULT '🖼️',
  "label" TEXT NOT NULL DEFAULT '',
  "category" TEXT NOT NULL DEFAULT 'match',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "gallery_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "push_subscriptions" (
  "id" TEXT NOT NULL,
  "endpoint" TEXT NOT NULL,
  "p256dh" TEXT NOT NULL,
  "auth" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE ("endpoint")
);

CREATE TABLE IF NOT EXISTS "live_state" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "data" JSONB,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "live_state_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "live_state_id_check" CHECK ("id" = 1)
);

-- Foreign Keys
ALTER TABLE "teams"        ADD CONSTRAINT "teams_groupId_fkey"         FOREIGN KEY ("groupId")  REFERENCES "groups"("id") ON DELETE SET NULL;
ALTER TABLE "squad_members" ADD CONSTRAINT "squad_members_teamId_fkey"  FOREIGN KEY ("teamId")   REFERENCES "teams"("id")  ON DELETE CASCADE;
ALTER TABLE "matches"      ADD CONSTRAINT "matches_groupId_fkey"        FOREIGN KEY ("groupId")  REFERENCES "groups"("id") ON DELETE SET NULL;
ALTER TABLE "matches"      ADD CONSTRAINT "matches_team1Id_fkey"        FOREIGN KEY ("team1Id")  REFERENCES "teams"("id");
ALTER TABLE "matches"      ADD CONSTRAINT "matches_team2Id_fkey"        FOREIGN KEY ("team2Id")  REFERENCES "teams"("id");
ALTER TABLE "players"      ADD CONSTRAINT "players_teamId_fkey"         FOREIGN KEY ("teamId")   REFERENCES "teams"("id")  ON DELETE SET NULL;
ALTER TABLE "ball_events"  ADD CONSTRAINT "ball_events_matchId_fkey"    FOREIGN KEY ("matchId")  REFERENCES "matches"("id") ON DELETE CASCADE;
ALTER TABLE "sentiments"   ADD CONSTRAINT "sentiments_matchId_fkey"     FOREIGN KEY ("matchId")  REFERENCES "matches"("id") ON DELETE CASCADE;
ALTER TABLE "sentiments"   ADD CONSTRAINT "sentiments_teamId_fkey"      FOREIGN KEY ("teamId")   REFERENCES "teams"("id")  ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS "matches_status_idx"      ON "matches"("status");
CREATE INDEX IF NOT EXISTS "squad_members_teamId_idx" ON "squad_members"("teamId");
CREATE INDEX IF NOT EXISTS "players_teamId_idx"       ON "players"("teamId");
CREATE INDEX IF NOT EXISTS "ball_events_matchId_idx"  ON "ball_events"("matchId");
CREATE INDEX IF NOT EXISTS "sentiments_matchId_idx"   ON "sentiments"("matchId");

-- Initial live_state row
INSERT INTO "live_state"("id","data","updatedAt") VALUES(1, NULL, NOW()) ON CONFLICT DO NOTHING;
